# write me a github action that deploy a WCF service to App Service
name: Deploy WCF Service to Azure App Service

on:
  push:
    branches:
      - master
    paths:
      - 'src/SoapLegacyService/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: 'src/SoapLegacyService'
  NUGET_VERSION: '5.3.x'

jobs:
  deploy-wcf-service:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main  
      
      - name: Install Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: ${{ env.NUGET_VERSION}}

      - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
        run: nuget restore
        working-directory: AZURE_WEBAPP_PACKAGE_PATH
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Run MSBuild
        run: msbuild .\SoapLegacyService.sln
        working-directory: AZURE_WEBAPP_PACKAGE_PATH
        
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}          

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'